### ISSUE TITLE
Docker and Makefile

### ISSUE THREAD

**Issue by lordsarcastic** [philipokiokio/fin-banker#1]
Docker support should be added to ensure ease of bootstrapping on any OS of choice. Also a Makefile will be useful so we don't have to memorize commands.

**Comment by philipokiokio** [comment]
Thanks chief.


I will look into that.

**Comment by philipokiokio** [comment]
Hey Chief.


Docker support added.
Makefile seems weird to me can you point me to your go to resource on it.
